# Enhanced Wikipedia Agent Configuration

# Large Language Model Configuration
llm:
  model_name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  temperature: 0.7
  max_tokens: 512
  top_p: 0.9
  top_k: 50
  repetition_penalty: 1.1
  device: "auto"  # auto, cpu, cuda
  trust_remote_code: true
  load_in_4bit: false  # Set to true for memory optimization
  
# Agent Configuration
agent:
  confidence_threshold: 0.6
  max_search_results: 5
  max_iterations: 10
  enable_caching: true
  cache_duration: 3600  # 1 hour in seconds
  similarity_threshold: 0.85
  max_conversation_history: 50
  enable_memory: true
  
# Knowledge Sources Configuration
sources:
  wikipedia:
    enabled: true
    top_k_results: 3
    lang: "en"
    load_all_available_meta: false
    doc_content_chars_max: 4000
    
  duckduckgo:
    enabled: true
    max_results: 5
    region: "us-en"
    safesearch: "moderate"  # strict, moderate, off
    timelimit: null  # d, w, m, y for day, week, month, year
    
  wolfram_alpha:
    enabled: true
    timeout: 30
    assume_timeout: 10
    include_pods: ["Result", "Solution"]
    
# Query Classification
classification:
  confidence_threshold: 0.7
  categories:
    - "factual"
    - "computational"
    - "current_events"
    - "conversational"
    - "complex_reasoning"
    
# Caching Configuration
cache:
  type: "disk"  # memory, disk, redis
  max_size: 1000  # Maximum number of cached responses
  ttl: 3600  # Time to live in seconds
  directory: "./cache"
  
# Memory Configuration
memory:
  type: "conversation_buffer"  # conversation_buffer, conversation_summary
  max_token_limit: 2000
  return_messages: true
  
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/agent.log"
  console: true
  max_bytes: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Performance Monitoring
monitoring:
  enabled: true
  metrics_file: "logs/metrics.json"
  track_response_time: true
  track_api_usage: true
  track_confidence_scores: true
  track_cache_hits: true
  
# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 1  # seconds
  fallback_enabled: true
  graceful_degradation: true
  
# API Rate Limiting
rate_limiting:
  wikipedia:
    requests_per_minute: 60
    burst_size: 10
    
  duckduckgo:
    requests_per_minute: 30
    burst_size: 5
    
  wolfram_alpha:
    requests_per_minute: 20
    burst_size: 3
    
# User Interface
ui:
  show_confidence: true
  show_sources: true
  show_reasoning: true
  colored_output: true
  progress_bars: true
  
# Development Settings
development:
  debug_mode: false
  verbose_logging: false
  save_intermediate_results: false
  profile_performance: false